apiVersion: batch/v1
kind: Job
metadata:
  name: topic-create-kube
spec:
  template:
    spec:
      containers:
      - name: topic-create
        image: quay.io/strimzi/kafka:0.35.1-kafka-3.4.0
        command: ["./bin/kafka-topics.sh", "--bootstrap-server", "kafka-no-keeper-bootstrap:9092", "--delete", "--topic", "names"]
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
      restartPolicy: Never
